### ISSUE TITLE
Pass the filename to the CSS parser

### ISSUE THREAD

**Issue by paazmaya** [frontendfriends/node-combine-mq#10]
Since the source file is specified in `options.src`, it would be helpful for the possible error messages, that it would be passed to the parser in https://github.com/frontendfriends/node-combine-mq/blob/master/lib/combine-mq.js#L209
as documented here
https://github.com/reworkcss/css#cssparsecode-options

**Comment by furzeface** [comment]
Thanks @paazmaya - will try and get round to this, unless you fancy having a go and submitting a PR?
Dan.

**Comment by paazmaya** [comment]
@furzeface #12 
Could not really test, as it seems that the tests are not running the plugin, but matching two files from the repository...
