### ISSUE TITLE
Why bundle cssbeautify?

### ISSUE THREAD

**Issue by ben-eb** [frontendfriends/node-combine-mq#18]
It detracts from the scope of the module, which is just to combine media queries together. Node modules should be small, focused and efficient. Do one thing and do it well.

**Comment by furzeface** [comment]
I agree for sure. This was done as a feature request for someone a while back, But yes next time I think I should be more assertive about these things and focus on what this module needs to do. Thanks!

**Comment by ben-eb** [comment]
Rather than closing the issue, a better solution would be to remove this functionality and release a new major version. :wink:

**Comment by furzeface** [comment]
Aha, but wouldn't that be blindly accepting another feature request? Something that I've now learnt from... :wink: 

Feel free to prepare a PR for things like this though if you feel it's the right thing to do! Because I do appreciate the advice on the right way to do these things :+1:

**Comment by ben-eb** [comment]
Also, it would make more sense architecturally speaking if we are to convert this to use PostCSS. A PostCSS plugin should take in an AST and return the transformed AST, not a string of CSS. :smiley:

https://github.com/frontendfriends/node-combine-mq/issues/11

Yep, not having some features is also a feature. This is why if we do this change, we should do a major version bump.

**Comment by furzeface** [comment]
I think I'm going to book some time to work on this and a few other modules for a personal development day at work soon. 

It'd be good to collaborate on some ideas and hopefully give it a good overhaul!
