### ISSUE TITLE
node 0.12 warning

### ISSUE THREAD

**Issue by PJL101** [frontendfriends/node-combine-mq#8]
When installing on node 0.12 (stable):

npm WARN engine combine-mq@0.6.0: wanted: {"node":"v0.10.x"} (current: {"node":"0.12.0","npm":"2.5.1"})

Not a huge problem but would be good to fix.

**Comment by furzeface** [comment]
Fix it Phil!!

**Comment by PJL101** [comment]
Pull request has been done.
